name: "custom GITHUB_ENV var Demo"

on: workflow_dispatch

jobs:
  custom-github-env-var-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: Use the value
        id: step_two
        run: |
          echo "$action_state"  #This will output  'yellow'
